### ISSUE TITLE
不支持arm64-v8a

### ISSUE THREAD

**Issue by wh19990906** [qq326646683/flutter_tencentplayer#130]
打包arm64_b8a，真机播放视频闪退

**Comment by wh19990906** [comment]
插件版本：1.2.0

**Comment by wh19990906** [comment]
E/AndroidRuntime(26170): java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
E/AndroidRuntime(26170): 	at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
E/AndroidRuntime(26170): 	at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:405)
E/AndroidRuntime(26170): 	at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(TXCDRApi.java:384)
E/AndroidRuntime(26170): 	at com.tencent.rtmp.TXVodPlayer.startPlay(TXVodPlayer.java:193)
E/AndroidRuntime(26170): 	at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin$TencentPlayer$3.run(FlutterTencentplayerPlugin.java:204)
E/AndroidRuntime(26170): 	at java.lang.Thread.run(Thread.java:923)
