### ISSUE TITLE
自动续播的时候出现oom

### ISSUE THREAD

**Issue by king418** [qq326646683/flutter_tencentplayer#41]
07-09 14:48:23.366 18141-18141/com.jinxian.flutter_tencentplayer_example E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.OutOfMemoryError
        at com.tencent.ijk.media.player.IjkMediaPlayer._prepareAsync(Native Method)
        at com.tencent.ijk.media.player.IjkMediaPlayer.prepareAsync(IjkMediaPlayer.java:530)
        at com.tencent.ijk.media.player.MediaPlayerProxy.prepareAsync(MediaPlayerProxy.java:98)
        at com.tencent.liteav.txcvodplayer.TXCVodVideoView.f(TXCVodVideoView.java:477)
        at com.tencent.liteav.txcvodplayer.TXCVodVideoView.setVideoURI(TXCVodVideoView.java:321)
        at com.tencent.liteav.txcvodplayer.TXCVodVideoView.setVideoPath(TXCVodVideoView.java:306)
        at com.tencent.liteav.f.a(TXCVodPlayer.java:101)
        at com.tencent.rtmp.TXVodPlayer.startPlay(TXVodPlayer.java:228)
        at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin$TencentPlayer.setPlaySource(FlutterTencentplayerPlugin.java:193)
        at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin$TencentPlayer.<init>(FlutterTencentplayerPlugin.java:82)
        at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin.onMethodCall(FlutterTencentplayerPlugin.java:473)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:5110)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by qq326646683** [comment]
我用demo里自动播放，播放了46集，没有出现oom

**Comment by qq326646683** [comment]
后来怎么样了

**Comment by qq326646683** [comment]
没有问题我给关掉了
