### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Wiki1991** [qq326646683/flutter_tencentplayer#91]
真机，打开本地相册的视频，debugger和Note的命令运行都闪退

```shell
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1440], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.0)
[√] Connected device (2 available)
```

错误日志
```shell
I/Timeline( 6595): Timeline: Activity_launch_request time:68064972 intent:Intent { act=android.intent.action.GET_CONTENT typ=video/* }
D/ActivityResultListener( 6595): requestCode=2352, resultCode = -1, intent = Intent { dat=content://com.android.providers.media.documents/document/video:29070 flg=0x1 }
W/Activity( 6595): Slow Operation: Activity com.example.huicunquzheng.test/.MainActivity onActivityResult took 364ms
I/flutter ( 6595): /data/user/0/com.example.huicunquzheng.test/cache/image_picker2227655931666915331.jpg
W/Native-LiteAV( 6595): load library txffmpeg from system path
W/Native-LiteAV( 6595): load library txffmpeg true
W/Native-LiteAV( 6595): load library traeimp-rtmp from system path
W/Native-LiteAV( 6595): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.huicunquzheng.test-kSdifrdEvUPFtgOcnrWhGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.huicunquzheng.test-kSdifrdEvUPFtgOcnrWhGw==/lib/arm64, /data/app/com.example.huicunquzheng.test-kSdifrdEvUPFtgOcnrWhGw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libtraeimp-rtmp.so"
W/Native-LiteAV( 6595): load library traeimp-rtmp false
W/Native-LiteAV( 6595): load library liteavsdk from system path
W/JNI_UTIL( 6595): JniHelper::setJavaVM(0x7275ac8f40), thread = 493846377800
I/JNI_UTIL( 6595): JniHelper::cacheEnv when no cache in thread = 493846377800
D/JNI_UTIL( 6595): JniHelper::GetEnv JNI_OK cache env 0x7275ae8460
I/Native-LiteAV( 6595):  ################ liteavsdk 8.2.9809 arm64 ###############
W/Native-LiteAV( 6595): load library liteavsdk true
I/TXCLog  ( 6595): TXCLog init log file path : /storage/emulated/0/Android/data/com.example.huicunquzheng.test/files/log/tencent/liteav, cache : /data/user/0/com.example.huicunquzheng.test/files/log/tencent/liteav
E/flutter ( 6595): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoSuchMethodError: no static method "Lcom/tencent/liteav/basic/log/TXCLog;.log_callback(ILjava/lang/String;Ljava/lang/String;)V"
E/flutter ( 6595): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6595): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter ( 6595): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter ( 6595):
F/flutter ( 6595): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).
F/libc    ( 6595): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 6595 (cunquzheng.test), pid 6595 (cunquzheng.test)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/nitrogen/nitrogen:9/PKQ1.181007.001/V11.0.3.0.PEDCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 6595, tid: 6595, name: cunquzheng.test  >>> com.example.huicunquzheng.test <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).
'
    x0  0000000000000000  x1  00000000000019c3  x2  0000000000000006  x3  0000000000000008
    x4  0000000000008000  x5  0000000000008000  x6  0000000000008000  x7  0080000000000000
    x8  0000000000000083  x9  afaf9d448961acba  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000008  x14 ffffffffffffffff  x15 00006c90f7ff4e20
    x16 00000072f9fef2b8  x17 00000072f9f0ec50  x18 0000000000000010  x19 00000000000019c3
    x20 00000000000019c3  x21 0000007ff11c3b58  x22 0000007275ae6298  x23 0000000000000000
    x24 0000000000000036  x25 0000007ff11c3e60  x26 00000072fb89b5e0  x27 0000000000000036
    x28 0000000000000001  x29 0000007ff11c3b40
    sp  0000007ff11c3b00  lr  00000072f9f020c4  pc  00000072f9f020ec
backtrace:
    #00 pc 00000000000220ec  /system/lib64/libc.so (abort+116)
    #01 pc 0000000001287244  /data/app/com.example.huicunquzheng.test-kSdifrdEvUPFtgOcnrWhGw==/lib/arm64/libflutter.so (offset 0x126e000)
    #02 pc 00000000000020dc  [anon:.bss:000000725a8f2000]
Lost connection to device.
```

**Comment by Wiki1991** [comment]
> 真机，打开本地相册的视频，debugger和Note的命令运行都闪退
> 
> `[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1440], locale zh-CN) [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) [√] Android Studio (version 4.0) [√] VS Code (version 1.50.0) [√] Connected device (2 available)`
> 
> 错误日志
> 
> `I/Timeline( 6595): Timeline: Activity_launch_request time:68064972 intent:Intent { act=android.intent.action.GET_CONTENT typ=video/* } D/ActivityResultListener( 6595): requestCode=2352, resultCode = -1, intent = Intent { dat=content://com.android.providers.media.documents/document/video:29070 flg=0x1 } W/Activity( 6595): Slow Operation: Activity com.example.huicunquzheng.test/.MainActivity onActivityResult took 364ms I/flutter ( 6595): /data/user/0/com.example.huicunquzheng.test/cache/image_picker2227655931666915331.jpg W/Native-LiteAV( 6595): load library txffmpeg from system path W/Native-LiteAV( 6595): load library txffmpeg true W/Native-LiteAV( 6595): load library traeimp-rtmp from system path W/Native-LiteAV( 6595): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.huicunquzheng.test-kSdifrdEvUPFtgOcnrWhGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.huicunquzheng.test-kSdifrdEvUPFtgOcnrWhGw==/lib/arm64, /data/app/com.example.huicunquzheng.test-kSdifrdEvUPFtgOcnrWhGw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libtraeimp-rtmp.so" W/Native-LiteAV( 6595): load library traeimp-rtmp false W/Native-LiteAV( 6595): load library liteavsdk from system path W/JNI_UTIL( 6595): JniHelper::setJavaVM(0x7275ac8f40), thread = 493846377800 I/JNI_UTIL( 6595): JniHelper::cacheEnv when no cache in thread = 493846377800 D/JNI_UTIL( 6595): JniHelper::GetEnv JNI_OK cache env 0x7275ae8460 `

**Comment by qq326646683** [comment]
不好意思，最近工作有些忙，没时间看这个。
这个闪退有必先步骤吗？我这边用flutter2.0.3运行了下，file视频-选择本地视频播放正常

**Comment by qq326646683** [comment]
可以运行最新代码试试，需要再open issue
